resolver: lts-5.11

flags: {}

extra-deps:
  - ghcjs-dom-0.2.3.1
  - haskell-src-exts-1.16.0.1
  - reflex-0.4.0
  - reflex-dom-0.3
  - ref-tf-0.4

extra-package-dbs: []

compiler: ghcjs-0.2.0.20160424_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160424_ghc-7.10.2:
        url: "http://ghcjs.luite.com/master-20160424.tar.gz"
